#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Liquider
  class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    40,    40,    40,     7,    43,    10,    57,    23,    38,    39,
    26,     6,    18,    20,    19,    21,    22,     3,    55,    23,
    27,    41,    41,    41,    18,    20,    19,    21,    22,    23,
    36,    37,    38,    39,    18,    20,    19,    21,    22,    23,
    38,    39,    36,    37,    18,    20,    19,    21,    22,    23,
    36,    37,    36,    37,    18,    20,    19,    21,    22,    23,
    36,    37,    36,    37,    18,    20,    19,    21,    22,    23,
    36,    37,    36,    37,    18,    20,    19,    21,    22,    23,
    28,    11,    58,   nil,    18,    20,    19,    21,    22,    23,
   nil,   nil,   nil,   nil,    18,    20,    19,    21,    22,    23,
   nil,   nil,   nil,   nil,    18,    20,    19,    21,    22,    23,
   nil,   nil,   nil,   nil,    18,    20,    19,    21,    22,    23,
   nil,   nil,   nil,   nil,    18,    20,    19,    21,    22,    23,
   nil,   nil,   nil,   nil,    18,    20,    19,    21,    22,    23,
   nil,   nil,   nil,   nil,    18,    20,    19,    21,    22,    23,
   nil,     7,   nil,    10,    18,    20,    19,    21,    22,     6,
    29,    30,    31,    32,    33,    34,    35 ]

racc_action_check = [
    53,    54,    16,     0,    25,     0,    42,    36,    51,    51,
     9,     0,    36,    36,    36,    36,    36,     0,    40,    41,
    10,    53,    54,    16,    41,    41,    41,    41,    41,    39,
    45,    45,    15,    15,    39,    39,    39,    39,    39,    38,
    52,    52,    14,    14,    38,    38,    38,    38,    38,    37,
    50,    50,    49,    49,    37,    37,    37,    37,    37,     7,
    44,    44,    48,    48,     7,     7,     7,     7,     7,    33,
    46,    46,    47,    47,    33,    33,    33,    33,    33,     3,
    11,     1,    56,   nil,     3,     3,     3,     3,     3,    23,
   nil,   nil,   nil,   nil,    23,    23,    23,    23,    23,    34,
   nil,   nil,   nil,   nil,    34,    34,    34,    34,    34,    29,
   nil,   nil,   nil,   nil,    29,    29,    29,    29,    29,    30,
   nil,   nil,   nil,   nil,    30,    30,    30,    30,    30,    31,
   nil,   nil,   nil,   nil,    31,    31,    31,    31,    31,    32,
   nil,   nil,   nil,   nil,    32,    32,    32,    32,    32,    35,
   nil,     4,   nil,     4,    35,    35,    35,    35,    35,     4,
    13,    13,    13,    13,    13,    13,    13 ]

racc_action_pointer = [
   -15,    81,   nil,    57,   133,   nil,   nil,    37,   nil,   -11,
    -7,    80,   nil,   149,    33,    25,    -1,   nil,   nil,   nil,
   nil,   nil,   nil,    67,   nil,   -15,   nil,   nil,   nil,    87,
    97,   107,   117,    47,    77,   127,   -15,    27,    17,     7,
    -9,    -3,   -17,   nil,    51,    21,    61,    63,    53,    43,
    41,     1,    33,    -3,    -2,   nil,    57,   nil,   nil ]

racc_action_default = [
    -3,   -36,    -1,   -36,    -4,    -5,    -7,   -36,    -9,   -36,
   -36,   -36,    -2,   -10,   -11,   -19,   -22,   -25,   -28,   -29,
   -30,   -31,   -32,   -36,    -6,   -36,   -34,   -35,    59,   -36,
   -36,   -36,   -36,   -36,   -36,   -36,   -36,   -36,   -36,   -36,
   -36,   -36,   -36,    -8,   -12,   -13,   -14,   -15,   -16,   -17,
   -18,   -20,   -21,   -23,   -24,   -26,   -36,   -33,   -27 ]

racc_goto_table = [
    12,    51,    52,     4,    25,    44,    45,    46,    47,    48,
    49,    50,     5,    53,    54,     2,    24,     1,   nil,   nil,
    42,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    56 ]

racc_goto_check = [
     3,     9,     9,     4,     3,     8,     8,     8,     8,     8,
     8,     8,     5,    10,    10,     2,     5,     1,   nil,   nil,
     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,    17,    15,    -3,     3,    12,   nil,   nil,   -24,   -35,
   -25,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,     8,    13,    14,    15,
    16,    17,     9 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 35, :_reduce_none,
  2, 35, :_reduce_2,
  0, 36, :_reduce_3,
  1, 36, :_reduce_4,
  1, 38, :_reduce_none,
  2, 38, :_reduce_6,
  1, 39, :_reduce_7,
  3, 39, :_reduce_8,
  1, 39, :_reduce_none,
  1, 37, :_reduce_none,
  1, 41, :_reduce_none,
  3, 41, :_reduce_12,
  3, 41, :_reduce_13,
  3, 41, :_reduce_14,
  3, 41, :_reduce_15,
  3, 41, :_reduce_16,
  3, 41, :_reduce_17,
  3, 41, :_reduce_18,
  1, 42, :_reduce_none,
  3, 42, :_reduce_20,
  3, 42, :_reduce_21,
  1, 43, :_reduce_none,
  3, 43, :_reduce_23,
  3, 43, :_reduce_24,
  1, 44, :_reduce_none,
  3, 44, :_reduce_26,
  4, 44, :_reduce_27,
  1, 45, :_reduce_28,
  1, 45, :_reduce_29,
  1, 45, :_reduce_30,
  1, 45, :_reduce_31,
  1, 45, :_reduce_32,
  3, 45, :_reduce_33,
  2, 40, :_reduce_none,
  2, 46, :_reduce_35 ]

racc_reduce_n = 36

racc_shift_n = 59

racc_token_table = {
  false => 0,
  :error => 1,
  :PIPE => 2,
  :DOT => 3,
  :DOTDOT => 4,
  :COLON => 5,
  :COMMA => 6,
  :TIMES => 7,
  :DIV => 8,
  :PLUS => 9,
  :MINUS => 10,
  :EQ => 11,
  :NE => 12,
  :LT => 13,
  :LE => 14,
  :GT => 15,
  :GE => 16,
  :CONTAINS => 17,
  :MUSTACHEOPEN => 18,
  :MUSTACHECLOSE => 19,
  :TAGOPEN => 20,
  :TAGCLOSE => 21,
  :PARENOPEN => 22,
  :PARENCLOSE => 23,
  :BRACKETOPEN => 24,
  :BRACKETCLOSE => 25,
  :TEXT => 26,
  :IDENT => 27,
  :NUMBER => 28,
  :STRING => 29,
  :TRUE => 30,
  :FALSE => 31,
  :GOTO_EXPRESSION => 32,
  :GOTO_ARGLIST => 33 }

racc_nt_base = 34

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "PIPE",
  "DOT",
  "DOTDOT",
  "COLON",
  "COMMA",
  "TIMES",
  "DIV",
  "PLUS",
  "MINUS",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "CONTAINS",
  "MUSTACHEOPEN",
  "MUSTACHECLOSE",
  "TAGOPEN",
  "TAGCLOSE",
  "PARENOPEN",
  "PARENCLOSE",
  "BRACKETOPEN",
  "BRACKETCLOSE",
  "TEXT",
  "IDENT",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "GOTO_EXPRESSION",
  "GOTO_ARGLIST",
  "$start",
  "Liquid",
  "Document",
  "Expression",
  "DocumentElementList",
  "DocumentElement",
  "Tag",
  "ComparisonExpression",
  "AdditiveExpression",
  "MultiplicativeExpression",
  "CallExpression",
  "PrimaryExpression",
  "TagLeader" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'liquid.y', 18)
  def _reduce_2(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 23)
  def _reduce_3(val, _values, result)
     result = Ast::DocumentNode.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 24)
  def _reduce_4(val, _values, result)
     result = Ast::DocumentNode.new([val].flatten) 
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'liquid.y', 29)
  def _reduce_6(val, _values, result)
     result = val.flatten 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 33)
  def _reduce_7(val, _values, result)
     result = Ast::TextNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 34)
  def _reduce_8(val, _values, result)
     result = Ast::MustacheNode.new(val[1]) 
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'liquid.y', 44)
  def _reduce_12(val, _values, result)
     result = Ast::BinOpNode.new(:==, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 45)
  def _reduce_13(val, _values, result)
     result = Ast::BinOpNode.new(:!=, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 46)
  def _reduce_14(val, _values, result)
     result = Ast::BinOpNode.new(:<, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 47)
  def _reduce_15(val, _values, result)
     result = Ast::BinOpNode.new(:<=, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 48)
  def _reduce_16(val, _values, result)
     result = Ast::BinOpNode.new(:>, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 49)
  def _reduce_17(val, _values, result)
     result = Ast::BinOpNode.new(:>=, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 50)
  def _reduce_18(val, _values, result)
     result = Ast::BinOpNode.new(:contains, val[0], val[2]) 
    result
  end
.,.,

# reduce 19 omitted

module_eval(<<'.,.,', 'liquid.y', 55)
  def _reduce_20(val, _values, result)
     result = Ast::BinOpNode.new(:+, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 56)
  def _reduce_21(val, _values, result)
     result = Ast::BinOpNode.new(:-, val[0], val[2], :-) 
    result
  end
.,.,

# reduce 22 omitted

module_eval(<<'.,.,', 'liquid.y', 61)
  def _reduce_23(val, _values, result)
     result = Ast::BinOpNode.new(:*, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 62)
  def _reduce_24(val, _values, result)
     result = Ast::BinOpNode.new(:'/', val[0], val[2]) 
    result
  end
.,.,

# reduce 25 omitted

module_eval(<<'.,.,', 'liquid.y', 67)
  def _reduce_26(val, _values, result)
     result = Ast::CallNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 68)
  def _reduce_27(val, _values, result)
     result = Ast::IndexNode.new(val[0], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 72)
  def _reduce_28(val, _values, result)
     result = Ast::SymbolNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 73)
  def _reduce_29(val, _values, result)
     result = Ast::StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 74)
  def _reduce_30(val, _values, result)
     result = Ast::NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 75)
  def _reduce_31(val, _values, result)
     result = Ast::BooleanNode.new(true) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 76)
  def _reduce_32(val, _values, result)
     result = Ast::BooleanNode.new(false) 
    result
  end
.,.,

module_eval(<<'.,.,', 'liquid.y', 77)
  def _reduce_33(val, _values, result)
     result = Ast::ParenthesisedNode.new(val[1]) 
    result
  end
.,.,

# reduce 34 omitted

module_eval(<<'.,.,', 'liquid.y', 86)
  def _reduce_35(val, _values, result)
          parse_tag val[1]
      # tag_class = tags[tag_name]
      # raise LiquiderSyntaxError, "Unknown tag '#{tag_name}'." unless tag_class

      # markup_parser = tag_class.markup_parser.new(tag_name, tags)
      # markup = markup_parser.parse(MarkupView.new(source_scanner))
      # return tag_class.build(tag_name, markup) unless tag_class.block?

      # body_parser = tag_class.body_parser.new(tag_name, tags)
      # body = body_parser.parse(BodyView.new(source_scanner)
      # tag_class.build(tag_name, markup, body)
    
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class GeneratedParser
  end   # module Liquider
